/**
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - name
 *         - email
 *         - password
 *         - role
 *         - verificationStatus
 *       properties:
 *         name:
 *           type: string
 *           description: The user's name
 *         email:
 *           type: string
 *           description: The user's email address
 *         phoneNumber:
 *           type: string
 *           description: The user's phone number
 *         password:
 *           type: string
 *           description: The user's password
 *         role:
 *           type: string
 *           enum: [CLIENT, FREELANCER, ADMIN]
 *           description: The user's role
 *         verificationStatus:
 *           type: string
 *           enum: [VERIFIED, UNVERIFIED]
 *           description: The verification status of the user
 *         twoFactorEnabled:
 *           type: boolean
 *           description: Whether two-factor authentication is enabled
 *       example:
 *         name: John Doe
 *         email: johndoe@example.com
 *         phoneNumber: "1234567890"
 *         password: "password123"
 *         role: CLIENT
 *         verificationStatus: VERIFIED
 *         twoFactorEnabled: false
 */

/**
 * @swagger
 * /api/register:
 *   post:
 *     summary: Register a new user
 *     tags: [User]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *     responses:
 *       201:
 *         description: User registered successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: User registered successfully
 *                 user:
 *                   $ref: '#/components/schemas/User'
 *       400:
 *         description: Invalid input or email already in use
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Email is already in use
 *       500:
 *         description: Server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: An error occurred during registration
 */

/**
 * @swagger
 * /api/2fa/setup:
 *   post:
 *     summary: Set up two-factor authentication for a user
 *     tags: [User]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               userId:
 *                 type: string
 *                 description: The ID of the user setting up 2FA
 *             required:
 *               - userId
 *             example:
 *               userId: "123e4567-e89b-12d3-a456-426614174000"
 *     responses:
 *       200:
 *         description: 2FA setup successful with a QR code for Google Authenticator
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 qrCode:
 *                   type: string
 *                   format: uri
 *                   description: Data URL of the QR code for setting up 2FA
 *                 message:
 *                   type: string
 *                   example: 2FA setup successfully
 *       400:
 *         description: Invalid input or user not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: User not found
 *       500:
 *         description: Server error during 2FA setup
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Error setting up 2FA
 */

/**
 * @swagger
 * /api/2fa/verify:
 *   post:
 *     summary: Verify a two-factor authentication code for a user
 *     tags: [User]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               userId:
 *                 type: string
 *                 description: The ID of the user verifying 2FA
 *               token:
 *                 type: string
 *                 description: The TOTP code generated by the authenticator app
 *             required:
 *               - userId
 *               - token
 *             example:
 *               userId: "123e4567-e89b-12d3-a456-426614174000"
 *               token: "123456"
 *     responses:
 *       200:
 *         description: 2FA code verified successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: 2FA code verified successfully
 *       400:
 *         description: Invalid 2FA code or 2FA not set up for the user
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Invalid 2FA code
 *       500:
 *         description: Server error during 2FA verification
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Error verifying 2FA code
 */

/**
 * @swagger
 * /api/users:
 *   get:
 *     summary: Retrieve a list of users
 *     tags: [User]
 *     responses:
 *       200:
 *         description: List of users retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/User'
 *       500:
 *         description: Server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: An error occurred while retrieving users
 */

/**
 * @swagger
 * /api/users/{id}:
 *   get:
 *     summary: Retrieve a user by ID
 *     tags: [User]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *         description: The user ID
 *     responses:
 *       200:
 *         description: User retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/User'
 *       404:
 *         description: User not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: User not found
 *       500:
 *         description: Server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: An error occurred while retrieving the user
 */

/**
 * @swagger
 * /api/users/{id}:
 *   put:
 *     summary: Update a user by ID
 *     tags: [User]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *         description: The user ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *     responses:
 *       200:
 *         description: User updated successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/User'
 *       400:
 *         description: Invalid input or user not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: User not found or invalid input
 *       500:
 *         description: Server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: An error occurred while updating the user
 */

/**
 * @swagger
 * /api/users/{id}:
 *   delete:
 *     summary: Remove a user by their unique ID
 *     tags: [User]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *         description: Unique identifier of the user to be deleted
 *     responses:
 *       204:
 *         description: User successfully deleted
 *       404:
 *         description: User not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: User not found
 *       500:
 *         description: An error occurred on the server while attempting to delete the user
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: An error occurred while deleting the user
 */

/**
 * @swagger
 * components:
 *   schemas:
 *     Job:
 *       type: object
 *       required:
 *         - title
 *         - description
 *         - category
 *         - location
 *         - budgetMin
 *         - budgetMax
 *         - status
 *       properties:
 *         title:
 *           type: string
 *           description: The job's title
 *         description:
 *           type: string
 *           description: A detailed description of the job
 *         category:
 *           type: string
 *           description: The category of the job (e.g., Web Development, Design)
 *         location:
 *           type: string
 *           description: Job location (Remote or On-site)
 *         budgetMin:
 *           type: number
 *           description: The minimum budget for the job
 *         budgetMax:
 *           type: number
 *           description: The maximum budget for the job
 *         status:
 *           type: string
 *           enum: [PENDING, ACTIVE, COMPLETED, DISPUTED]
 *           description: The status of the job
 *       example:
 *         title: "Website Development"
 *         description: "Looking for a developer to build a company website"
 *         category: "Web Development"
 *         location: "Remote"
 *         budgetMin: 500
 *         budgetMax: 1500
 *         status: "PENDING"
 */

/**
 * @swagger
 * /api/jobs/all:
 *   get:
 *     summary: Retrieve a list of all jobs
 *     tags: [Job]
 *     responses:
 *       200:
 *         description: List of jobs retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Job'
 *       500:
 *         description: Server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: An error occurred while retrieving jobs
 */

/**
 * @swagger
 * /api/jobs:
 *   get:
 *     summary: Retrieve jobs filtered by status
 *     tags: [Job]
 *     parameters:
 *       - in: query
 *         name: status
 *         schema:
 *           type: string
 *           enum: [PENDING, ACTIVE, COMPLETED, DISPUTED]
 *         description: Filter jobs by status
 *     responses:
 *       200:
 *         description: List of filtered jobs retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Job'
 *       400:
 *         description: Invalid status parameter
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Invalid status parameter
 *       500:
 *         description: Server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: An error occurred while retrieving jobs by status
 */
