/**
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - name
 *         - email
 *         - password
 *         - role
 *         - verificationStatus
 *       properties:
 *         name:
 *           type: string
 *           description: The user's name
 *         email:
 *           type: string
 *           description: The user's email address
 *         phoneNumber:
 *           type: string
 *           description: The user's phone number
 *         password:
 *           type: string
 *           description: The user's password
 *         role:
 *           type: string
 *           enum: [CLIENT, FREELANCER, ADMIN]
 *           description: The user's role
 *         verificationStatus:
 *           type: string
 *           enum: [VERIFIED, UNVERIFIED]
 *           description: The verification status of the user
 *         twoFactorEnabled:
 *           type: boolean
 *           description: Whether two-factor authentication is enabled
 *       example:
 *         name: John Doe
 *         email: johndoe@example.com
 *         phoneNumber: "1234567890"
 *         password: "password123"
 *         role: CLIENT
 *         verificationStatus: VERIFIED
 *         twoFactorEnabled: false
 */

/**
 * @swagger
 * /api/register:
 *   post:
 *     summary: Register a new user
 *     tags: [User]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/User'
 *     responses:
 *       201:
 *         description: User registered successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: User registered successfully
 *                 user:
 *                   $ref: '#/components/schemas/User'
 *       400:
 *         description: Invalid input or email already in use
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Email is already in use
 *       500:
 *         description: Server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: An error occurred during registration
 */

/**
 * @swagger
 * /api/2fa/setup:
 *   post:
 *     summary: Set up two-factor authentication for a user
 *     tags: [User]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               userId:
 *                 type: string
 *                 description: The ID of the user setting up 2FA
 *             required:
 *               - userId
 *             example:
 *               userId: "123e4567-e89b-12d3-a456-426614174000"
 *     responses:
 *       200:
 *         description: 2FA setup successful with a QR code for Google Authenticator
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 qrCode:
 *                   type: string
 *                   format: uri
 *                   description: Data URL of the QR code for setting up 2FA
 *                 message:
 *                   type: string
 *                   example: 2FA setup successfully
 *       400:
 *         description: Invalid input or user not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: User not found
 *       500:
 *         description: Server error during 2FA setup
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Error setting up 2FA
 */

/**
 * @swagger
 * /api/2fa/verify:
 *   post:
 *     summary: Verify a two-factor authentication code for a user
 *     tags: [User]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               userId:
 *                 type: string
 *                 description: The ID of the user verifying 2FA
 *               token:
 *                 type: string
 *                 description: The TOTP code generated by the authenticator app
 *             required:
 *               - userId
 *               - token
 *             example:
 *               userId: "123e4567-e89b-12d3-a456-426614174000"
 *               token: "123456"
 *     responses:
 *       200:
 *         description: 2FA code verified successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: 2FA code verified successfully
 *       400:
 *         description: Invalid 2FA code or 2FA not set up for the user
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Invalid 2FA code
 *       500:
 *         description: Server error during 2FA verification
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: Error verifying 2FA code
 */
